<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Platforms>AnyCPU;x64</Platforms>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="FreeSpire.Presentation" Version="11.4.0" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
    <PackageReference Include="ShapeCrawler" Version="0.80.0" />
  </ItemGroup>

  <ItemGroup>
    <None Update="nanto-n-bai-template(1).pptx">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="nanto-n-bai-template.pptx">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
